stages:
  - test
  - documentation

# # This job tests the ThreadPinning.jl with Julia 1.6 on Noctua 1
# julia/1.6-n1:
#   stage: test
#   tags:
#     - bauerc-noctua
#   variables:
#     SCHEDULER_PARAMETERS: "-N 1 -n 1 -c 40 -t 00:15:00 -A pc2-mitarbeiter -p normal --exclusive"
#     JULIA_NUM_THREADS: "20"
#   rules:
#     - changes:
#       - "README.md"
#     #   - "docs/**/*.md"
#     #   - "docs/make.jl"
#     #   - "docs/build_docs.jl"
#     #   when: never
#     - when: on_success
#   script:
#     - /bin/bash -l
#     - module load lang
#     - module load Julia/1.6.6-linux-x86_64
#     - julia --color=yes --project=. -e 'using Pkg; Pkg.build(verbose=true); Pkg.test(; coverage = false);'

# This job tests the ThreadPinning.jl with Julia 1.6 on Noctua 2
julia/1.6-n2:
  stage: test
  tags:
    - bauerc-noctua2
  variables:
    SCHEDULER_PARAMETERS: "-N 1 -n 1 -c 128 -t 00:15:00 -A pc2-mitarbeiter -p fpga --exclusive"
    JULIA_NUM_THREADS: "64"
  rules:
    - changes:
      - "README.md"
    #   - "docs/**/*.md"
    #   - "docs/make.jl"
    #   - "docs/build_docs.jl"
    #   when: never
    - when: on_success
  script:
    - /bin/bash -l
    - module load lang
    - module load Julia/1.6.6-linux-x86_64
    - julia --color=yes --project=. -e 'using Pkg; Pkg.build(verbose=true); Pkg.test(; coverage = false);'

# This job tests the ThreadPinning.jl with Julia 1.8 if the 1.6 job has passed
# + generates and submits code coverage to codecov.io
julia/1.8-n1:
  stage: test
  tags:
    - bauerc-noctua
  variables:
    SCHEDULER_PARAMETERS: "-N 1 -n 1 -c 40 -t 00:15:00 -A pc2-mitarbeiter -p normal --exclusive"
    JULIA_NUM_THREADS: "20"
  rules:
    - changes:
      - "README.md"
    - when: on_success
#   needs:
#     job: julia/1.6-n1
  script:
    - /bin/bash -l
    - module load lang/JuliaHPC/1.8.3-foss-2022a-CUDA-11.7.0
    - julia --color=yes --project=. -e 'using Pkg; Pkg.build(verbose=true); Pkg.test(; coverage = true);'
    - julia --color=yes --project=test/coverage -e 'import Pkg; Pkg.instantiate()'
    - julia --color=yes --project=test/coverage test/coverage/coverage.jl

# Documentation
build-and-deploy:
  stage: documentation
  tags:
    - bauerc-noctua
  variables:
    SCHEDULER_PARAMETERS: "-N 1 -n 1 -c 40 -t 00:15:00 -A pc2-mitarbeiter -p normal --exclusive"
    JULIA_NUM_THREADS: "20"
  only:
    - main
    - pushes
    - tags
    - external_pull_requests
  needs:
    job: julia/1.8-n1
  script:
    - /bin/bash -l
    - module load lang/JuliaHPC/1.8.3-foss-2022a-CUDA-11.7.0
    - cd docs
    - julia --color=yes build_docs.jl
  allow_failure: false
