stages:
  - test
  - documentation
variables:
  SCHEDULER_PARAMETERS: "-N 1 -n 1 -c 40 -t 00:15:00 -A pc2-mitarbeiter -p fpga --exclusive"
  JULIA_DEPOT_PATH: "/scratch/pc2-mitarbeiter/bauerc/.julia-ci"
  JULIA_NUM_THREADS: "20"
  JULIA_1_9: "lang/JuliaHPC/1.9.1-foss-2022a-CUDA-11.7.0"
default:
  tags:
    - bauerc-noctua

julia/1.9:
  stage: test
  rules:
    - changes:
        - "README.md"
    - when: on_success
  script:
    - /bin/bash -l
    - module load $JULIA_1_9
    - julia --color=yes --project=. -e 'using Pkg; Pkg.build(verbose=true); Pkg.test(; coverage = false);'
  allow_failure: false

# Documentation
build-and-deploy:
  stage: documentation
  only:
    - main
    - pushes
    - tags
    - external_pull_requests
  script:
    - /bin/bash -l
    - module load $JULIA_1_9
    - cd docs
    - julia --color=yes build_docs.jl
  allow_failure: false
