stages:
  - test

# This job tests the ThreadPinning.jl with Julia 1.6
# + generates and submits code coverage to codecov.io
julia/1.6:
  stage: test
  tags:
    - bauerc-noctua
  variables:
    SCHEDULER_PARAMETERS: "-A pc2-mitarbeiter -p short"
  rules:
    - changes:
      - "README.md"
    #   - "docs/**/*.md"
    #   - "docs/make.jl"
    #   - "docs/build_docs.jl"
    #   when: never
    - when: on_success
  script:
    - export JULIA_NUM_THREADS=20
    - /bin/bash -l
    - module load lang/Julia/1.6.5-linux-x86_64
    - julia --color=yes --project=. -e 'using Pkg; Pkg.build(verbose=true); Pkg.test(; coverage = true);'
    - julia --color=yes --project=test/coverage -e 'import Pkg; Pkg.instantiate()'
    - julia --color=yes --project=test/coverage test/coverage/coverage.jl

# This job tests the ThreadPinning.jl with Julia 1.7 if the 1.6 job has passed
julia/1.7:
  stage: test
  tags:
    - bauerc-noctua
  variables:
    SCHEDULER_PARAMETERS: "-A pc2-mitarbeiter -p short"
  rules:
    - changes:
      - "README.md"
    - when: on_success
  needs:
    job: julia/1.6
  script:
    - export JULIA_NUM_THREADS=20
    - /bin/bash -l
    - module load lang/Julia/1.7.1-linux-x86_64
    - julia --color=yes --project=. -e 'using Pkg; Pkg.build(verbose=true); Pkg.test(; coverage = true);'
  allow_failure: true
